[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[providers]
  [providers.file]
    filename = "./domains.toml"
    watch = true

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints.web]
  address = ":80"

  [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "web-secure"
        scheme = "https"

[entryPoints.web-secure]
  address = ":443"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  [accessLog.filters]
    statusCodes = "404"

[certificatesResolvers.sample.acme]
  email = "youremail@domain.com"
  storage = "acme.json"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.sample.acme.dnsChallenge]
    provider = "cloudflare"
